// ReactJSLearning/node-mongo-react/src/App.js
import logo from './logo.svg';
import './App.css';
import axios from 'axios';
import { useState, useEffect } from 'react';
import "font-awesome/css/font-awesome.min.css";

function App() {
  const [table_data, updateTable] = useState([]);
  const [name, updateName] = useState("");
  const [city, updateCity] = useState("");

  useEffect(() => {
    getData();
  }, []);

  function getData() {
    axios.get("http://localhost:5000/getData").then(res => {
      console.log(res.data);
      if (res.data && res.data.records) {
        updateTable(res.data.records);
      }
    });
  }

  function handleDelete(un) {
    alert("Deleting: " + un);
    axios.post("http://localhost:5000/deleteData", { uname: un }).then(res => {
      console.log(res.data);
      getData();
    });
  }

  function insertData() {
    var obj = { uname: name, city: city };
    axios.post("http://localhost:5000/postData", obj).then((res) => {
      console.log(res.data.result);
      alert(res.data.result);
      getData();
      updateCity("");
      updateName("");
    });
  }

  return (
    <div className="App">
      <div className='container'>
        <br />
        <input
          type='text'
          placeholder='Enter Name'
          className='form-control'
          value={name}
          onChange={(t) => updateName(t.target.value)}
        />
        <br />
        <input
          type='text'
          placeholder='Enter City'
          className='form-control'
          value={city}
          onChange={(t) => updateCity(t.target.value)}
        />
        <br />
        <button className='btn btn-primary' onClick={insertData}>Insert</button>
      </div>
      <table className="table table-striped">
        <tbody>
          {table_data.map((oneRow, idx) => (
            <tr key={idx}>
              <td>{oneRow.uname}</td>
              <td>{oneRow.city}</td>
              <td>
                <span
                  className='fa fa-trash'
                  style={{ color: 'red', cursor: 'pointer' }}
                  onClick={() => handleDelete(oneRow.uname)}
                ></span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default App;

// Angular/crud-app/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  standalone: false,
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'crud-app';
  txtName: string = '';
  txtCity: string = '';
  btnTxt = 'Insert';
  red_id = '';
  table_data: any;

  constructor(private ht: HttpClient) {}

  ngOnInit(): void {
    this.funGetData();
  }

  funGetData() {
    this.ht.get("http://localhost:4000/getData").subscribe((dt: any) => {
      this.table_data = dt;
    });
  }

  funInsert() {
    if (this.btnTxt === 'Insert') {
      const obj = { uname: this.txtName, city: this.txtCity };
      this.ht.post("http://localhost:4000/insertData", obj, { responseType: 'text' })
        .subscribe((dt: string) => {
          alert(dt);
          this.funGetData();
          this.txtName = '';
          this.txtCity = '';
        }, err => {
          console.error("Insert error:", err);
        });
    } else {
      const obj = { oid: this.red_id, un: this.txtName, ct: this.txtCity };
      this.ht.post("http://localhost:4000/update", obj)
        .subscribe((dt: any) => {
          alert(dt.result);
          this.btnTxt = 'Insert';
          this.txtName = '';
          this.txtCity = '';
          this.funGetData();
        }, err => {
          console.error("Update error:", err);
        });
    }
  }

  funTrash(rid: string) {
    const ob = { _id: rid };
    this.ht.post("http://localhost:4000/deleteData", ob)
      .subscribe((dt: any) => {
        alert(dt.result);
        this.funGetData();
      }, err => {
        console.error("Delete error:", err);
        alert("Delete failed");
      });
  }

  funUpdate(rdata: any) {
    this.txtName = rdata.uname;
    this.txtCity = rdata.city;
    this.red_id = rdata._id;
    this.btnTxt = 'Save';
  }

}

<!-- Hi
<input type="button" value="Get Data" (click)="funGetData()"/>

{{table_data|json}} -->

<div class="container">
  <br/>
  <input type="text" placeholder="Username" class="form-control" [(ngModel)]="txtName"/>
  <br/>
  <input type="text" placeholder="City" class="form-control" [(ngModel)]="txtCity"/>
  <br/>
  <input type="button" value="{{btnTxt}}" class="btn btn-primary" (click)="funInsert()"/>
</div>
<table border="1" class="table table-striped" >
   <thead>
      <th>Id</th>
      <th>Name</th>
      <th>City</th>
    </thead>
        <tbody>

  <tr *ngFor="let un of table_data">
      <td>{{un._id}}</td>
      <td>{{un.uname}}</td>
      <td>{{un.city}}</td>

      <td><span class="fa fa-trash" (click)="funTrash(un._id)"></span></td>
      <td><span class="fa fa-edit" (click)="funUpdate(un)"></span></td>
      
  </tr>
      </tbody>

</table>
